spring:
  application:
    name: learnSpringWebFlux
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/learnWebflux
    username: yongseopkim
    password: qkdrhd`12
  webflux:
    base-path: /api

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080

